Backend1/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # path('', views.index, name='index'),
    path('demo', views.demo, name='demo'),
    # path('demo2', views.demo2, name='demo2'),
    path('',views.demo2,name='demo2'),
    path('add',views.Create_a_Post,name='Add_Post'),
    path('save-Ad' , views.Save_Post_TO_DB , name='Save_Post_TO_DB'),
    path('Profile/<int:pk>/' , views.SpecificUser , name='SpecificUser'),
    path('view-post/<int:pk>/' , views.view_post , name='view_post'),
    path('favourite-post/<int:pk>/',views.favourite_post,name='favourite_post'),
    path('comment-post/<int:pk>/',views.comment_post,name='comment_post'),
    path('search/',views.search,name='search'),
    path('Liked/<int:pk>/',views.Liked_posts,name='Liked_posts'),
    path('Saved/<int:pk>/',views.saved_posts,name='saved_posts'),
    path('Followers/<int:pk>/',views.followers,name='followers'),
    path('Following/<int:pk>/',views.following,name='following'),
    path('getFreePhotos/',views.getFreePhotos,name='Free_photograph'),
    path('getFreePhotograph/',views.getFreePhotograph,name='Free_photograph_form'),
    path('unlock-free-photos/',views.unlock_free_photos_post_ad,name='unlock_free_photos_post_ad'),
    path('order-details/',views.order_details,name='photography_order_details'),
    path('order-confirmed/',views.order_confirmed,name='photography_order_confirmed'),
    path('no-new-photos/',views.come_back_later,name='come_back_later'),
    path('new-post-or-not/',views.Another_Post_or_Not,name='Another_Post_or_Not'),
    
    


    # API URLS
    path('api/view_All_Ads/',views.View_ALL_Post,name='API-View'),
    path('api/get_categories/',views.Get_categories,name='API-Categories'),
    path('api/like_post/',views.like_post,name='API-Like'),
    path('api/HidePost/',views.HidePost,name = 'API-HidePost'),
    path('api/get_post_availablity',views.get_post_availablity,name='API-Product-available-at'),
    path('api/savePost',views.favouritePost,name='API-SavePost'),
    path('api/follow-user/',views.follow_user,name="API-FollowUser"),
    path('api/get_comments/',views.get_comments,name="API-GetComments"),

]

Netfoto_Portal/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^admin/login', your_custom_login_view, name='custom_login_page_admin'),

    path('', include('Backend1.urls')),
    path('members/', include('members.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login_me_in/', views.login_user, name='login-in'),
    path('logout_me_out/', views.logout_user, name='logout-out'),
    path('register_user/', views.register_user, name='register-user'),
    # path('verify-email/',views.verify_email,name='verify-email-username'),
    path('verify-email/<str:username>/ ', views.verify_email, name='verify-email'), 
    path('resend-email/', views.resend_email, name='resend-email'),
    path('profile/', views.User_Profile, name='User_Profile'),
    path('first/', views.first, name='first'),
    path('api/CheckEmail',views.CheckEmail,name='CheckEmail'),
    path('api/checkOTP',views.check_OTP,name='checkOTP'),
    path('login_register/', views.login_register, name='login_register'),
    path('reset-password/',views.reset_password,name = 'reset_password'),
    
    
    path('api/check_username',views.check_username,name="UsernameAvailability")

]

Backend1/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    Created_By = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255,null=True)
    Created_date = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return self.title

class ProductAvailability(models.Model):
    title = models.CharField(max_length=255,null=True)
    Created_date = models.DateTimeField(auto_now_add=True)
    Updated_date = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return self.title

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    # category = models.ForeignKey(Category, on_delete=models.PROTECT)
    ProductAvailability = models.ForeignKey(ProductAvailability, on_delete=models.PROTECT, null=True, blank=True)
    title = models.CharField(max_length=255,null=True)   
    description = models.CharField(max_length=1000,null=True)
    Likes = models.ManyToManyField(to=User, related_name='Post_likes')
    favourites = models.ManyToManyField(to=User,blank=True,related_name="favourite")
    Tag1 = models.CharField(max_length=255,null=True,blank=True)
    Tag2 = models.CharField(max_length=255,null=True,blank=True)
    product_details = models.CharField(max_length=1000,null=True,blank=True)
    Tag3 = models.CharField(max_length = 255, null = True, blank = True)
    Tag1_Name = models.CharField(max_length=255,null=True,blank=True)
    Tag2_Name = models.CharField(max_length=255,null=True,blank=True)
    Tag3_Name = models.CharField(max_length=255,null=True,blank=True)
    users = models.ManyToManyField(User, related_name='users_hidden_from_post')
    Created_date = models.DateTimeField(auto_now_add=True)
    Updated_date = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return self.title

    def likesCount(self):
        return self.Likes.count()

    def get_absolute_url(self):
        #return reverse('Blog_Details', args=(str(self.id)))   # to return to the specific blog post details 
        return reverse('home') 

class People(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='people')
    Name = models.CharField(max_length=255,null=True)
    # email = models.EmailField(max_length=255,null=False,unique=True,blank=False)
    is_verified = models.BooleanField(default=False)
    OTP = models.CharField(max_length=6, null=True, blank=True)
    following = models.ManyToManyField(to=User, related_name='following', blank=True)
    photo = models.ImageField(upload_to='profile_pics', blank=True,null=True)
    Phone_number = models.CharField(max_length=255,null=True,blank=True)
    Birth_Date = models.DateField(null=True,blank=True)
    step_1 = models.BooleanField(default=False)
    step_2 = models.BooleanField(default=False)
    step_3 = models.BooleanField(default=False)
    stages = models.TextField(default='',blank=True)

    Created_date = models.DateTimeField(auto_now_add=True)
    Updated_date = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return self.user.email


class Images(models.Model):
    Post = models.ForeignKey(Post,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/')


class Comment(models.Model):
    comment = models.TextField(null=True)
    Created_date = models.DateTimeField(auto_now_add=True)
    Updated_date = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments_user')

    def __str__(self):
        return self.comment




class Stage1(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Company_Name = models.CharField(max_length=255,null=True)
    GST_number = models.CharField(max_length=255,null=True)
    Company_Address1 = models.CharField(max_length=255,null=True)
    Company_Address2 = models.CharField(max_length=255,null=True)
    City = models.CharField(max_length=255,null=True)
    State = models.CharField(max_length=255,null=True)
    pinCode = models.CharField(max_length=255,null=True)
    About = models.CharField(max_length=255,null=True)

class product_details(models.Model):
    people = models.ForeignKey(People, on_delete=models.CASCADE)
    Product_Name = models.CharField(max_length=255,null=True)
    no_of_products = models.IntegerField(null=True)
    no_of_views = models.IntegerField(null=True)
    send_products = models.CharField(max_length=255,null=True)
    send_products_back = models.CharField(max_length=255,null=True)
    product_additional_specifications = models.TextField(null=True)
    #orderID = models.CharField(max_length=255,null=True)
    updated_date = models.DateTimeField(auto_now=True)

class product_orders(models.Model):
    orderID = models.CharField(max_length=255,null=True)
    people = models.ForeignKey(People, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)



class Claim_free_photos_questions(models.Model):
    phase = models.IntegerField()
    question = models.CharField(max_length=255,null=True)

class Test(models.Model):
    myName = models.CharField(max_length=255,null=True)

Backend1/templates/Another_Post_or_Not.html
{% extends 'Base.html'%} {% load static%} {% block styles %}
<link rel="stylesheet" href="{% static 'FrontEnd1/css/Order_details.css' %}" />
{% endblock %} {% block title %} Order Details {% endblock %} 
{% block content %}
    want to add a new post or want to continue?

    <a href="{% url 'unlock_free_photos_post_ad' %}">
    <button>
            post a new ad
        </button>
    </a>

    <a href="{% url 'photography_order_details' %}">
    <button>
            continue without posting a new ad
        </button>
    </a>
{% endblock %}

Backend1/templates/Create_a_Post.html
{% extends 'Base.html'%}
{% load static%}
{% block styles %}
<link rel="stylesheet" href="{% static 'FrontEnd1/css/Create_a_Post.css' %}">
{% endblock %}
{% block title %}
    List of Blogs from create a post
{% endblock %}
{% block content %}
  <section>
    <form id="regForm" action="{% url 'Save_Post_TO_DB' %}" method="POST" role="form" id="Ad-save-form" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="tab">
        <h1 class="text-center">
          Get Free Photographs:
        </h1>
        <div class="container1">
          <input type="file" id="file-input" name="files" onchange="preview()" multiple accept="image/*">
          <label for="file-input">
            <i class="fa fa-upload choose_photo">
            </i> &nbsp; Choose Your Photos
          </label>
          <p id="num-of-files">
            No Files Chosen
          </p>
          <div id="images-space">
          </div>
        </div>
      </div>
        
      <div class="tab" >
        <div class="container1">
        <div id = "images_2nd_div_heading">
        </div>
        <div id = "main_2nd_tab_div">
          <div id="images_2nd">
          </div>
        </div>

        <div id="Tags-div" class="text-center">
        </div>

        <p><input name = "Ad-title" placeholder="Write a Heading" oninput="this.className = ''"></p>
        <p><input name = "Ad-Desc" placeholder="Write a Description" oninput="this.className = ''"></p>
        <!-- <label for="category">Please Select you product Cateory</label> -->
          {% comment %} <select name="category" id="category" class="form-select">
            <option disabled selected value>Post Category</option>
          </select> {% endcomment %}
        </div>
      </div>

        <!-- Footer Buttons -->
      <div class="footer_buttons" id="Footer_Buttons">
        <button class="btn" type="button" id="prevBtn" onclick="nextPrev(-1)">
          <i class="fa fa-angle-left" aria-hidden="true">
          </i>
        </button>
        <button class="btn" type="button" id="nextBtn" onclick="nextPrev(1)" style="margin-top:10px;">
        </button>
      </div>
        

        <!-- <div class="footer-buttons">
          <div class="footer-buttons-div" >
            <div class="text-center">
              <button class="btn" type="button" id="prevBtn" onclick="nextPrev(-1)">
                <i class="fa fa-angle-left" aria-hidden="true">
                </i>
              </button>
            </div>
            <div style="background-color:black; width:60px; height:60px; border-radius:50%;" class="text-center">
              <button class="btn" type="button" id="nextBtn" onclick="nextPrev(1)" style="margin-top:10px;">
              </button>
            </div>
          </div>
        </div> -->
        
        <!-- Circles which indicates the steps of the form: -->
        <div style="text-align:center;margin-top:40px; display: none;">
          <span class="step"></span>
          <span class="step"></span>
        </div>    
        
        <!-- Modal Box -->
        <div class="modal fade" id="mymodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel" style="margin:auto;">Add URL</h5>
                <select name="Product_available_at" id="Product_available_at" class="form-select">
                  <option disabled></option>
                </select>
              </div>
              <div class="modal-body">
                <div id="modal-id-1">
                  <input name = "Tag1" id="Tag1" placeholder="Paste URL" style="margin-bottom:2px;">
                  <input name = "Tag1-Name" id="Tag1-Name" placeholder="Rename URL">
                </div>
                <div id="modal-id-2">
                  <hr>
                  <input name="Tag2" id="Tag2" placeholder="Paste URL" style="margin-bottom:2px;">
                  <input name="Tag2-Name" id="Tag2-Name" placeholder="Rename URL">
                </div>
                <div id="modal-id-3">
                  <hr>
                  <input name = "Tag3" id="Tag3" placeholder="Paste URL" style="margin-bottom:2px;">
                  <input name = "Tag3-Name" id="Tag3-Name" placeholder="Rename URL">
                </div>
              </div>
              <div class="text-center">
                <i class="fa fa-plus-circle font-awesome-class" onclick="first_click();" id="first"></i>
                <i class="fa fa-plus-circle font-awesome-class" onclick="second_click();" id="second"></i>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" onclick="show_tags();">Insert Tags</button>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="background-color:gray; padding:10px; border-radius:50%;"></button>
              </div>
            </div>
          </div>
        </div>
    </form>
  </section>
  <br>
  <br>
  
      {% endblock%}
      {% block scripts %}
<script src="{% static 'FrontEnd1/js/Create_a_Post.js' %}"></script>
<script>
  $(document).ready(function(){
    // $.ajax({
    //   url: "{% url 'API-Categories' %}",
    //   type: "GET",
    //   dataType: "json",
    //   success: function(data){
    //     //console.log(data);
    //     var html = "";
    //     $.each(data, function(index, value){
    //       //console.log('INDEX ->' , index)
    //       //console.log('VALUE ->' , value.title)
    //       html += "<option value='"+value.id+"'>"+value.title+"</option>";
    //     });
    //     $("#category").append(html);
    //   }
    // });
    console.log('Hi');
    $.ajax({
      url: "{% url 'API-Product-available-at' %}",
      type: "GET",
      dataType: "json",
      success: function(data){
        console.log(data);
        var html = "";
        $.each(data, function(index, value){
          //console.log('INDEX ->' , index)
          //console.log('VALUE ->' , value.title)
          html += "<option value='"+value.id+"'>"+value.title+"</option>";
        });
        $("#Product_available_at").append(html);
      }
    });
    $("#modal-id-2").hide();
    $("#modal-id-3").hide();
    $("#second").hide();
});

function first_click(){
  $("#modal-id-2").show();
  $("#first").hide();
  $("#second").show();
}
function second_click(){
  $("#modal-id-3").show();
  $("#second").hide();
}

</script>
{% endblock %}

Backend1/templates/Demo.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<style>
  #myElement {
    background: silver;
    height: 300px;
    text-align: center;
    font: 30px/300px Helvetica, Arial, sans-serif;
  }
</style>
<body>

  <div id="myElement"></div>
  <script src="https://hammerjs.github.io/dist/hammer.js"></script>
  <script>
    var myElement = document.getElementById('myElement');
    console.log(myElement)
// create a simple instance
// by default, it only adds horizontal recognizers
var mc = new Hammer(myElement);

// listen to events...
mc.on("panleft panright tap press", function(ev) {
    myElement.textContent = ev.type +" gesture detected.";
});
</script>
</body>



</html>

Backend1/templates/FreePhotograph.html
{% extends 'base.html'%}
{% load static%}
{% block styles %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'FrontEnd1/css/getFreePhotograph.css' %}"
/>
{% endblock %} 

{% block title %} 
  Get Free Photos
{% endblock %}
    
{% block content %}
<!-- <h1>Unlock your 10 Free Product Photographs</h1> -->
<div class="main_free_photograph_form_div">
    <form method="POST" action="" id="company_details">
        {% csrf_token %}
        <div class="form-group">
            <label for="company_name">Company Name</label>
            <input type="text" name="Company_Name" placeholder="Company Name" required>
        </div>

        <div class="form-group">
            <label for="company_gst_number">GST Number</label>
            <input type="text" name="GST" placeholder="GST #" required>
        </div>

        <div class="form-group">
            <label for="company_address">Company Address</label>
            <input type="text" name="Company_Address1" placeholder="Address Line 1" required>
            <input type="text" name="Company_Address2" placeholder="Address Line 2" required>
        </div>

        <div class="form-group">
            <label for="company_city">City</label>
            <input type="text" name="City" placeholder="City" required>
        </div>

        <div class="form-group">
            <label for="company_state">State</label>
            <input type="text" name="State" placeholder="State" required>
        </div>

        <div class="form-group">
            <label for="company_pincode">Pincode</label>
            <input type="text" name="Pincode" placeholder="Pincode" required>
        </div>

        <div class="form-group">
            <label for="About">Please Tell us more about your company</label>
            <input type="text" name="About" placeholder="About Your Company" required>
        </div>
        <button type="submit" class="btn">Continue</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'FrontEnd1/js/getFreePhotograph.js' %}"></script>
{% endblock %}

Backend1/templates/Search.html
{% extends 'Base.html'%}
{% load static%}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'FrontEnd1/css/Search.css' %}">
{% endblock %}

{% block title %}
    List of Blogs
{% endblock %}

{% block content %}
<div class="container1 text-center">
{% comment %} <h1>Search any Ad Post</h1> {% endcomment %}
<form action="{% url 'search' %}" method="post">
    {% csrf_token %} 
    <input type="text" name="search_text" placeholder="Search 'Jewellery,packaging manufacturer' ">
    <input type="submit" value="Search">
</form>
</div>
{% endblock %}

Backend1/templates/Specific_User_Page.html
{% extends 'base.html'%} {% load static%} {% block styles %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'FrontEnd1/css/Specific_User_Page.css' %}"
/>
{% endblock %} {% block title %} List of Blogs from specific User page 
{% endblock %} {% block content %}
<div class="specific_user_main_div">
  <div class="top-header">
    <div style="visibility: hidden;">This</div>

    <div class="user-details">
      <div class="username_user">{{Data.username}}</div>

      <div class="user_photo">
        {% if Data.people_photo %}
        <div class="profile_image">
          <img src="{{Data.people_photo.url}}" alt="No photo" class="image_of_user"/>
        </div>
        {% else %}
        <div class="header_Image">
          <p class="first_char">{{Data.first_char}}</p>
        </div>
        {% endif %}
      </div>
    </div>

    <div class="header-setting-img">
      <img
        src='{% static "FrontEnd1/Static_Images/CovrPage_Like_R.png" %}'
        alt="" data-bs-toggle="modal" data-bs-target="#exampleModalCenter"
      />
    </div>
  </div>
  <div class="star_ratings">
    <div class="stars">
      <i class="fa fa-star" aria-hidden="true"></i>
      <i class="fa fa-star" aria-hidden="true"></i>
      <i class="fa fa-star" aria-hidden="true"></i>
      <i class="fa fa-star" aria-hidden="true"></i>
      <i class="fa fa-star" aria-hidden="true"></i>
    </div>
    <div class="all_reviews">See 436 reviews</div>
  </div>

  <div class="numbers_div">
    <div class="followers">
      <a href="{% url 'followers' Data.user_id %}">
        <div class="followers_number">{{Data.followers|length}}</div>
        <div>followers</div>
      </a>
    </div>
    <div class="following">
      <a href="{% url 'following' Data.user_id %}">
        <div class="following_number">{{Data.following|length}}</div>
        <div>following</div>
      </a>  
    </div>
    <div class="catalogues">
      <a href="#">  
        <div class="catalogues_number">{{Data.user_Ads|length}}</div>
        <div>Catalogues</div>
      </a>
    </div>
  </div>

  {% if Data.user_id != Data.current_user_id %} 
  <div class="buttons">
    {% comment %} {% if Data.isFollowed == True %} {% endcomment %}
    {% if Data.isFollowed == False %}
      <div class="user_my_account" id="" onclick="Follow_Unfollow({{Data.user_id}});">Follow</div>
    {% else %}
      <div class="user_my_account" onclick="Follow_Unfollow({{Data.user_id}})">Unfollow</div>
    {% endif %}
    <div class="user_edit_profile">Contact</div>
  </div>
  {% else %}
  <div class="buttons">
    <div class="user_my_account">Account</div>
    <div class="user_edit_profile">Edit Profile</div>
  </div>
  {% endif %}




  <div class="description_user">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid sed
    maxime, quas voluptatibus qui asperiores esse adipisci cupiditate autem
    neque quo iste architecto itaque modi ipsa perspiciatis nobis sit similique
    quaerat vel illum porro rerum? Rem atque saepe quia! Culpa vitae incidunt
    repellendus ab. Incidunt.
  </div>

    <div style="display: flex; justify-content: space-evenly; margin-top: 20px; margin-bottom: 20px;">
        <button data-tab-target = "#Catalogs" class="active tab btn">Catalogs</button>
        <button data-tab-target = "#About" class="tab btn">About</button>
    </div>
  <div class="Tabs_content">
      <div id="Catalogs" data-tab-content class="active">
          <div class="Catalogs">
          {% for i in Data.user_Ads %}
          <div style="text-align: center; margin-bottom:20px;">    
                {% for z in i.images_set.all %}
                    {%  if forloop.counter == 1 %}
                        <div class="cover_image_catalogue">
                            <a href="{% url 'view_post' i.id %}">
                                <img src="{{z.image.url}}" alt="">
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
                <div class="catalogue_title">
                    {{i.title}}
                </div>
            </div>
            
            {% endfor %}
      </div>
    </div>
      <div id="About" data-tab-content>
          <!-- {{Data.person}}{{Data.followers}} -->
          <!-- {{Data.following}} -->
        <p style="color:red; text-align: center;">Coming Up Soon</p>
      </div>
  </div>

  <!-- Modal Box -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      {% if Data.user_id == Data.current_user_id %}
      <div class="modal-body">
        <div class="profile_setting">
          <div class="first_div_profile_setting common_div_setting">
            <div class="" onclick="copy_profile_link({{Data.user_id}});">
              Copy Profile Link
            </div>
            <div class="">
              <i class="fa fa-link" aria-hidden="true"></i>
            </div>
          </div>
          <hr>
          <div class="second_div_profile_setting common_div_setting">
            <div>
              Settings
            </div>
            <div>
              <i class="fa fa-cog" aria-hidden="true"></i>
            </div>
          </div>
          <hr>
          <div class="third_div_profile_setting common_div_setting">
            <div>
              <a href="{% url 'saved_posts' Data.user_id %}">
                Saved
              </a>
            </div>
            <div>
              <a href="{% url 'saved_posts' Data.user_id %}">
                <i class="fa fa-bookmark" aria-hidden="true"></i>
              </a>
            </div>
          </div>
          <hr>
          <div class="fourth_div_profile_setting common_div_setting">
            <div>
              <a href="{% url 'Liked_posts' Data.user_id %}">
                Liked
              </a>
            </div>
            <div>
              <a href="{% url 'Liked_posts' Data.user_id %}">
                <i class="fa fa-heart" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div style="color:red; text-align: end; margin-top:10px; visibility: hidden;" id="copy_link_profile">Link Copied</div>
        <div class="close_setting">
          <i class="fa fa-times" aria-hidden="true" data-bs-dismiss="modal"></i>
        </div>
      </div>
      {% else %}
      <div>In progress</div>
      {% endif %}
    </div>
  </div>
</div>
  <!-- Till Here -->


</div>
{% endblock %}
{% block scripts %} 
<script src="{% static 'FrontEnd1/js/Specific_User_Page.js' %}"></script>
<script type="text/javascript">
  var follow_unfollow_user = "{% url 'API-FollowUser' %}";
  var csrfToken = "{{ csrf_token }}";
  $(document).ready(function(){
    console.log('ready');
  });
</script>
{% endblock %}

Backend1/templates/Stage3.html
<h1>Hello from stage 3</h1>

Backend1/templates/come_back_later.html
{% extends 'Base.html'%} {% load static%} {% block styles %}
<link rel="stylesheet" href="{% static 'FrontEnd1/css/Order_confirmation.css' %}" />
{% endblock %} {% block title %} Order Confirmation {% endblock %} 
{% block content %}
    <h1>Come back later for more free Photos</h1>
{% endblock %}

{% block scripts %}
{% endblock %}

Backend1/templates/followersList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello from followersList.html</h1>
    {{followers}}
    <div style="background-color:black; color:yellow; font-size:30px; text-align:center;">In Progress</div>
</body>
</html>